/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.mainframeUI;

import java.io.PrintWriter;
import java.net.Socket;
import model.Item;
import model.User;
import view.initloginUI.InitLoginJDialog;
import view.itemmanagerUI.ItemManagerUI;
import view.itemspanelUI.ItemsPanelUI;
import view.storeDialogUI.StoreDialogUI;

public class MainFrameUI extends javax.swing.JFrame implements view.itemmanagerUI.ItemManagerUI.ItemManagerDelegate, 
                                                               view.itemspanelUI.ItemsPanelUI.ItemsPanelDelegate,
                                                               view.initloginUI.InitLoginJDialog.LoginDelegate {
    private InitLoginJDialog login;
    public User currentUser; 
    public AppClient sellerClient;
    
    //LoginDelegate
    @Override
    public void loginWithUser(User user) {
        
        currentUser = user;
        jNameLabel.setText(user.GetID());
        
        itemsPanelUI1.inventoryList = user.inventory;
        itemsPanelUI1.updateTableView();
        itemsPanelUI1.setItemsPanelState(ItemsPanelUI.ItemsPaneState.ENABLED);
    }
    
    
    //ItemManagerDelegate 
    @Override
    public void itemManagerIsInEditMode() {
        System.out.println("EditMode"); 
        itemsPanelUI1.setItemsPanelState(ItemsPanelUI.ItemsPaneState.DISABLED);
        if(itemManagerUI1.managerState == ItemManagerUI.ManagerState.NEWITEMISBEINGCREATED) {
            itemsPanelUI1.deselectInventorySelection();
        }   
    }
    
    @Override
    public void itemManagerIsQuitEditMode() {
        System.out.println("EditMode"); 
        itemsPanelUI1.setItemsPanelState(ItemsPanelUI.ItemsPaneState.ENABLED);
    }
    
    @Override
    public void itemManagerCreatedNewItem(Item newItem) {
        if(itemManagerUI1.managerState == ItemManagerUI.ManagerState.NEWITEMISBEINGCREATED) {
            itemsPanelUI1.inventoryList.addNewItem(newItem);
            itemsPanelUI1.updateTableView();
        } else if(itemManagerUI1.managerState == ItemManagerUI.ManagerState.ITEMISBEINGEDITED) {
            Item selectedItem = itemsPanelUI1.getSelectedItem();
            selectedItem.transformIntoItem(newItem);
        }
    }
    
    //ItemSpaceDelegate 
    @Override
    public void inventoryItemSelected(Item selectedItem) {
        System.out.print(selectedItem.getItemName()); 
        itemManagerUI1.setManagerState(ItemManagerUI.ManagerState.INVENTORYITEMSELECTED);
        itemManagerUI1.SetItemInManager(selectedItem);
    }
    
    public void itemManagerDeletedItem() {
        itemsPanelUI1.removeSelectedItem();
    }
    
    /**
     * Creates new form MainFrameUI
     */
    public MainFrameUI() {
        initComponents();
        itemManagerUI1.setDelegate(this);
        itemsPanelUI1.setDelegate(this);
        
        login = new InitLoginJDialog(this,true);
        login.setDelegate(this);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        itemManagerUI1 = new view.itemmanagerUI.ItemManagerUI();
        itemsPanelUI1 = new view.itemspanelUI.ItemsPanelUI();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jNameLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPushUser = new javax.swing.JMenuItem();
        jOpenStore = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Account Name:");

        jLabel2.setText("Sales: $0.00");

        jNameLabel.setText("Null");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jNameLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(23, 23, 23))
        );

        jMenu1.setText("File");

        jMenuItem2.setText("Login");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jPushUser.setText("Push User");
        jPushUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPushUserActionPerformed(evt);
            }
        });
        jMenu1.add(jPushUser);

        jOpenStore.setText("Open Store");
        jOpenStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpenStoreActionPerformed(evt);
            }
        });
        jMenu1.add(jOpenStore);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemsPanelUI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(itemManagerUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(itemsPanelUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(itemManagerUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOpenStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpenStoreActionPerformed
        // TODO add your handling code here:
        StoreDialogUI store = new StoreDialogUI(this,true);
        store.setVisible(true);
    }//GEN-LAST:event_jOpenStoreActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        itemsPanelUI1.setItemsPanelState(ItemsPanelUI.ItemsPaneState.DISABLED);
        itemsPanelUI1.deselectInventorySelection();
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jPushUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPushUserActionPerformed
        // TODO add your handling code here:
        if(sellerClient == null && currentUser != null){
            
            System.out.println("HSHDHSJHDJSAHGDJHA");
        try {
            final int PORT = 1025;
            final String HOST = "localhost";
            Socket SOCK = new Socket (HOST,PORT);
            System.out.println("You Connected to: " + HOST);
            
            
            sellerClient = new AppClient(SOCK);
            
            PrintWriter OUT = new PrintWriter(SOCK.getOutputStream());
            OUT.println(this.currentUser.toJson());
            OUT.flush();
            
            Thread X = new Thread(sellerClient);
            X.start();
            
        }
        catch(Exception X) {
            System.out.println(X);
            
        }
        } else {
            if(currentUser != null && sellerClient != null) {
                sellerClient.SEND(this.currentUser.toJson());
            } else System.out.println("Pls Login With a User.");
        }
    }//GEN-LAST:event_jPushUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.itemmanagerUI.ItemManagerUI itemManagerUI1;
    private view.itemspanelUI.ItemsPanelUI itemsPanelUI1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel jNameLabel;
    private javax.swing.JMenuItem jOpenStore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jPushUser;
    // End of variables declaration//GEN-END:variables
    

}
